apiVersion: apps/v1
kind: Deployment
metadata:
  name: logo-tejarat
  namespace: seminar
  labels:
    app: logo-tejarat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logo-tejarat
  template:
    metadata:
      labels:
        app: logo-tejarat
    spec:
      containers:
        - name: nginx
          image: registry.sarvrayaneh.com/test/seminar-web:v3
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: nexus
