services:
  web:
    image: nginx:alpine
    container_name: seminar-web
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
